### ISSUE TITLE
Error Setting up Platform on 2021.8.0

### ISSUE THREAD

**Issue by jimcortez** [marthoc/homeseer#55]
I got this log when upgrading to 2021.8.0 from 2021.7.0. Seems all my other controls and sensors work. I am guessing this has something to do with the new energy monitoring.

```
Logger: homeassistant.setup
Source: setup.py:311
First occurred: 9:36:04 AM (1 occurrences)
Last logged: 9:36:04 AM

Unable to prepare setup for platform homeseer.sensor: Platform not found (cannot import name 'ELECTRICAL_CURRENT_AMPERE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
```

**Comment by sparkrussell** [comment]
I'm seeing the same issue with 2021.8.1 .  Net Effect is that no climate related sensors seem to load like entities for my Nest Thermostat, Z-Wave Temperature sensors and battery levels.  Z-Wave Lights seem to work just fine.

**Comment by marthoc** [comment]
I'm looking at this today as I'm facing the same issue. I think it's just that that constant was removed. I will be looking at the new energy features for a future release but for now I will just try to get it working again. Stay tuned.

**Comment by malosaa** [comment]
i have this issue asswell after the update, 

this is added in the logs.

Logger: homeassistant.setup
Source: setup.py:311
First occurred: 6:19:39 PM (1 occurrences)
Last logged: 6:19:39 PM

Unable to prepare setup for platform homeseer.sensor: Platform not found (cannot import name 'ELECTRICAL_CURRENT_AMPERE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

**Comment by kahancock** [comment]
Just adding a +1 to this. Seeing the same as all others. Lights work but no sensors are connected. Thanks!!
